autoservisas/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('cars/', views.cars, name='cars'),
    path('cars/<int:car_id>', views.car, name='car'),
    path('orders/', views.OrderListView.as_view(), name='orders'),
    path('orders/<int:pk>', views.OrderDetailView.as_view(), name='order-detail'),
    path('search/', views.search, name='search'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('myorders/', views.OrdersByUserListView.as_view(), name='my-orders'),
    path('myorders/<int:pk>', views.OrderByUserDetailView.as_view(), name='my-order'),
    path('myorders/new', views.OrderByUserCreateView.as_view(), name='my-orders-new'),
    path('myorders/<int:pk>/update', views.OrderByUserUpdateView.as_view(), name='my-order-update'),
    path('myorders/<int:pk>/delete', views.OrderByUserDeleteView.as_view(), name='my-order-delete'),
    path('myorders/orderline/<int:pk>', views.OrderLineByUserCreateView.as_view(), name='my-orderline'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('autoservisas/', include('autoservisas.urls')),
    path('', RedirectView.as_view(url='autoservisas/', permanent=True)),
    path('tinymce/', include('tinymce.urls')),
]+ (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

autoservisas/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import datetime
import pytz
from tinymce.models import HTMLField
from PIL import Image
utc = pytz.UTC
from django.utils.translation import gettext_lazy as _



# Create your models here.
class CarModel(models.Model):
    manufacturer = models.CharField(verbose_name=_('Manufacturer'), max_length=200, help_text='Enter Car manufacturer')
    model = models.CharField(verbose_name=_('Model'), max_length=200, help_text='Enter model name')

    def __str__(self):
        return f"{self.manufacturer} {self.model}"

    class Meta:
        verbose_name = 'Car Model'
        verbose_name_plural = 'Car Models'


class Car(models.Model):
    licence_plate = models.CharField(verbose_name=_('Licence plate'), max_length=10)
    owner = models.CharField(verbose_name=_('Owner'), null=True, max_length=200)
    vin_code = models.CharField(verbose_name=_('VIN code'), max_length=13)
    car_model = models.ForeignKey('CarModel', verbose_name=_('Model'), on_delete=models.SET_NULL, null=True, blank=True)
    cover = models.ImageField(_('Image'), upload_to='covers', null=True, blank=True)
    description = HTMLField(_('Description'), null=True, blank=True)

    def __str__(self):
        return f"{self.owner} {self.car_model} {self.licence_plate} {self.vin_code}"

    class Meta:
        verbose_name = 'Car'
        verbose_name_plural = 'Cars'


class Service(models.Model):
    name = models.CharField(verbose_name=_('Name'), max_length=200)
    price = models.FloatField(verbose_name=_('Price'))


    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Service'
        verbose_name_plural = 'Services'


class Order(models.Model):
    due_date = models.DateTimeField(verbose_name=_('Due Date'), null=True, blank=True)
    car = models.ForeignKey('Car', verbose_name=_('Car'), on_delete=models.SET_NULL, null=True)
    client = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)


    @property
    def is_overdue(self):
        if self.due_date and datetime.datetime.today().replace(tzinfo=utc) > self.due_date.replace(tzinfo=utc):
            return True
        return False

    @property
    def total_sum(self):
        sum = 0
        orderline = OrderLine.objects.filter(order=self.id)
        for line in orderline:
            sum += line.service.price * line.qty
        return sum

    def get_absolute_url(self):
        """Nurodo konkretaus aprašymo galinį adresą"""
        return reverse('order-detail', args=[str(self.id)])


    CAR_STATUS = (
        ('a', 'Approved'),
        ('p', 'Processing'),
        ('d', 'Done'),
        ('c', 'Canceled'),
    )

    status = models.CharField(
        max_length=1,
        choices=CAR_STATUS,
        blank=True,
        default='p',
        help_text='Status',
    )

    def __str__(self):
        return f"{self.car}: {self.car.owner}, {self.due_date}"

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

class OrderReview(models.Model):
    order = models.ForeignKey('Order', on_delete=models.SET_NULL, null=True, blank=True)
    reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField(_('Review'), max_length=2000)


class OrderLine(models.Model):
    order = models.ForeignKey('Order', verbose_name="Order", on_delete=models.CASCADE, null=True, related_name='lines')
    service = models.ForeignKey('Service', verbose_name="Service", on_delete=models.SET_NULL, null=True)
    qty = models.IntegerField(_("Quantity"))

    @property
    def item_sum(self):
        return self.service.price * self.qty

    def get_absolute_url(self):
        """Nurodo konkretaus aprašymo galinį adresą"""
        return reverse('order-detail', args=[str(self.id)])


    class Meta:
        verbose_name = 'Order Line'
        verbose_name_plural = 'Order Lines'


    def __str__(self):
        return f"{self.order}: {self.service}, {self.qty}"

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(default="default.png", upload_to="profile_pics")

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

    def __str__(self):
        return f"{self.user.username} profile"

    def save(self,  *args, **kwargs):
        super().save()
        img = Image.open(self.picture.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.picture.path)

autoservisas/forms.py
from .models import OrderReview
from django import forms
from .models import Profile
from django.contrib.auth.models import User

class OrderReviewForm(forms.ModelForm):
    class Meta:
        model = OrderReview
        fields = ('content', 'order', 'reviewer',)
        widgets = {'order': forms.HiddenInput(), 'reviewer': forms.HiddenInput()}

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['picture']

autoservisas/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponse
from .models import Car, CarModel, Order, Service,  OrderLine
from django.views import generic
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.contrib.auth.forms import User
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from .forms import OrderReviewForm
from django.views.generic.edit import FormMixin
from django.contrib.auth.decorators import login_required
from .forms import OrderReviewForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.mixins import UserPassesTestMixin
from django.utils.translation import gettext as _


# Create your views here.

def index(request):
    num_cars = Car.objects.all().count()
    num_models = CarModel.objects.all().count()

    # Laisvos knygos (tos, kurios turi statusą 'g')
    num_order_status = Order.objects.filter(status__exact='d').count()

    # Kiek yra autorių
    num_orders = Order.objects.count()

    num_services = Service.objects.count()
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1

    # perduodame informaciją į šabloną žodyno pavidale:
    context = {
        'num_cars': num_cars,
        'num_models': num_models,
        'num_order_status': num_order_status,
        'num_orders': num_orders,
        'num_services': num_services,
        'num_visits': num_visits,
    }

    # renderiname index.html, su duomenimis kintamąjame context
    return render(request, 'index.html', context=context)


def cars(request):
    paginator = Paginator(Car.objects.all(), 2)
    page_number = request.GET.get('page')
    paged_cars = paginator.get_page(page_number)
    context = {
        'cars': paged_cars
    }
    return render(request, 'cars.html', context=context)


def car(request, car_id):
    single_car = get_object_or_404(Car, pk=car_id)
    return render(request, 'car.html', {'car': single_car})


class OrderListView(generic.ListView):
    model = Order
    paginate_by = 1
    template_name = 'orders.html'


class OrderDetailView(FormMixin, generic.DetailView):
    model = Order
    template_name = 'order.html'
    form_class = OrderReviewForm

    class Meta:
        ordering = ['car']

    def get_success_url(self):
        return reverse('order-detail', kwargs={'pk': self.object.id})

    def get_context_data(self, *args, **kwargs):
        context = super(OrderDetailView, self).get_context_data(**kwargs)
        context['form'] = OrderReviewForm(initial={'order': self.object})
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.order = self.object
        form.instance.reviewer = self.request.user
        form.save()
        return super(OrderDetailView, self).form_valid(form)


def search(request):
    """
    paprasta paieška. query ima informaciją iš paieškos laukelio,
    search_results prafiltruoja pagal įvestą tekstą knygų pavadinimus ir aprašymus.
    Icontains nuo contains skiriasi tuo, kad icontains ignoruoja ar raidės
    didžiosios/mažosios.
    """
    query = request.GET.get('query')
    search_results = Car.objects.filter(Q(owner__icontains=query) | Q(vin_code__icontains=query) | Q(
        licence_plate__icontains=query) | Q(car_model__manufacturer__icontains=query) | Q(
        car_model__model__icontains=query))
    return render(request, 'search.html', {'cars': search_results, 'query': query})

class OrdersByUserListView(LoginRequiredMixin, generic.ListView):
    model = Order
    template_name = 'user_orders.html'

    def get_queryset(self):
        return Order.objects.filter(client=self.request.user).filter(status__exact='p').order_by('due_date')


class OrderByUserDetailView(FormMixin, LoginRequiredMixin, generic.DetailView):
    model = Order
    template_name = 'user_order.html'
    form_class = OrderReviewForm

    def get_success_url(self):
        return reverse('order-detail', kwargs={'pk': self.object.id})

    def get_context_data(self, *args, **kwargs):
        context = super(OrderByUserDetailView, self).get_context_data(**kwargs)
        context['form'] = OrderReviewForm(initial={'order': self.object})
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.order = self.object
        form.instance.reviewer = self.request.user
        form.save()
        return super(OrderByUserDetailView, self).form_valid(form)

class OrderByUserCreateView(LoginRequiredMixin, generic.CreateView):
    model = Order
    fields = ['car', 'due_date']
    success_url = "/autoservisas/myorders/"
    template_name = 'user_order_form.html'

    def form_valid(self, form):
        form.instance.client = self.request.user
        return super().form_valid(form)

class OrderByUserUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Order
    fields = ['car', 'due_date']
    success_url = "/autoservisas/myorders/"
    template_name = 'user_order_form.html'

    def form_valid(self, form):
        form.instance.client = self.request.user
        return super().form_valid(form)

    def test_func(self):
        car = self.get_object()
        return self.request.user == car.client

class OrderByUserDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Order
    success_url = "/autoservisas/myorders/"
    template_name = 'user_order_delete.html'

    def test_func(self):
        car = self.get_object()
        return self.request.user == car.client

class OrderLineByUserCreateView(LoginRequiredMixin, generic.CreateView):
    model = OrderLine
    fields = ['service', 'qty']
    template_name = 'user_orderline_form.html'

    def form_valid(self, form):
        form.instance.order = Order.objects.get(pk=self.kwargs['pk'])
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        pk = self.kwargs["pk"]
        return reverse("my-order", kwargs={"pk": pk})


@csrf_protect
def register(request):
    if request.method == "POST":
        # pasiimame reikšmes iš registracijos formos
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        # tikriname, ar sutampa slaptažodžiai
        if password == password2:
            # tikriname, ar neužimtas username
            if User.objects.filter(username=username).exists():
                messages.error(request, _('User name {} already in use!'.format(username)))
                return redirect('register')
            else:
                # tikriname, ar nėra tokio pat email
                if User.objects.filter(email=email).exists():
                    messages.error(request, _(f'Email {email} already in use!'))
                    return redirect('register')
                else:
                    # jeigu viskas tvarkoje, sukuriame naują vartotoją
                    User.objects.create_user(username=username, email=email, password=password)
        else:
            messages.error(request, _('Passwords do not match'))
            return redirect('register')
    return render(request, 'register.html')

@login_required
def profile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, _(f"Profile updated"))
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'profile.html', context)

autoservisas/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Autoservice</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
{% load i18n %}
      <form action="{% url 'set_language' %}" method="post">
        {% csrf_token %}
        <input name="next" type="hidden" value="{{ redirect_to }}"/>
        <select name="language" onchange="this.form.submit()">
          {% load static %}
          {% get_current_language as LANGUAGE_CODE %}
          {% get_available_languages as LANGUAGES %}
          {% for lang in LANGUAGES %}
          <option style="background-image: url({% static 'img/lt.png' %});" value="{{ lang.0 }}" {% if lang.0 == LANGUAGE_CODE %} selected="selected" {% endif %}>
            {{ lang.0 }}
          </option>
          {% endfor %}
        </select>
      </form>
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light static-top mb-5 shadow">
    <div class="container">
        <a class="navbar-brand" href="#">
            <svg class="bi bi-wrench" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor"
                 xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                      d="M.102 2.223A3.004 3.004 0 003.78 5.897l6.341 6.252A3.003 3.003 0 0013 16a3 3 0 10-.851-5.878L5.897 3.781A3.004 3.004 0 002.223.1l2.141 2.142L4 4l-1.757.364L.102 2.223zm13.37 9.019L13 11l-.471.242-.529.026-.287.445-.445.287-.026.529L11 13l.242.471.026.529.445.287.287.445.529.026L13 15l.471-.242.529-.026.287-.445.445-.287.026-.529L15 13l-.242-.471-.026-.529-.445-.287-.287-.445-.529-.026z"
                      clip-rule="evenodd"/>
            </svg>
            {% trans "Autoservice" %}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">{% trans "Home" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cars' %}">{% trans "Automobiliai" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'orders' %}">{% trans "Orders" %}</a>
                </li>
                <li>
                    <form action="{% url 'search' %}" method="get" class="form-inline my-2 my-md-0">
                        <input name="query" class="form-control" type="text" placeholder="Search">
                    </form>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'profile' %}">
                    <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                              d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z"
                              clip-rule="evenodd"/>
                    </svg>
                    {{ user.get_username }}</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'my-orders'%}">{% trans "My Orders" %}</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'my-orders-new'%}?next=/autoservisas">{% trans "New Order"%}</a></li>

                <li class="nav-item"><a class="nav-link" href="{% url 'logout'%}?next=/autoservisas">{% trans "Logout" %}</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'login'%}?next={{request.path}}">{% trans "Login" %}</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'register'%}">{% trans "Registration" %}</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

</body>
</html>

autoservisas/templates/car.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
{% load static %}
    <div class="container car">
        {% if car.cover %}
          <img src="{{ car.cover.url }}" class="card-img-top" alt="...">
        {% else %}
          <img src="{% static 'img/no-image.png' %}" class="card-img-top">
        {% endif %}
        <p>{% trans "Car Owner:" %}</strong>{{ car.owner }}</p>
        <p>{% trans "Car Model:" %}</strong>{{ car.car_model }} </p>
        <p>{% trans "Licence plate:" %}</strong>{{ car.licence_plate }}</p>
        <p>{% trans "VIN code:" %}</strong>{{ car.vin_code }}</p>
        <p>{% trans "Description:"%}{{ car.description | safe }}</p>
    </div>
{% endblock %}

autoservisas/templates/index.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <h1>{% trans "The Best Car Service in Town" %}</h1>
  <p>{% trans "Welcome to car paradise!" %}</p>
  <p>{% trans "At the moment:" %}</p>
  <ul>
    <li><strong>{% trans "Services:" %}</strong> {{ num_services }}</li>
    <li><strong>{% trans "Cars:" %}</strong> {{ num_cars }}</li>
    <li><strong>{% trans "Orders:" %}</strong> {{ num_orders }}</li>
    <li><strong>{% trans "Orders status:" %}</strong> {{ num_order_status }}</li>
    <li><strong>{% trans "Car Models:" %}</strong> {{ num_models }}</li>
  </ul>
<p>{% trans "Your visits:" %} {{ num_visits }}</p>
{% endblock %}

autoservisas/templates/order.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div class="container car">
    <p><strong>{% trans "Car: "%}</strong> {{ order.car }} </p>
    <p><strong>{% trans "Due date: "%}</strong>{{ order.due_date }}</p>
</div>

<div style="margin-left:20px;margin-top:20px">
    <h4>{% trans "Services:"%}</h4>
    {% for orderline in order.lines.all %}
    <hr>
    <p>{{ orderline.service }} - {{orderline.qty}}{% trans "pcs. Total: "%} {{orderline.item_sum}} </p>
    {% endfor %}
    <p><strong>{% trans "Total: "%}</strong> {{ order.total_sum }} </p>
    </br>
    <h4>{% trans "Reviews:"%}</h4>
    {% if order.orderreview_set.all %}
    {% for review in order.orderreview_set.all %}
    <hr>
    <strong>{{ review.reviewer }}</strong>, <em>{{ review.date_created}}</em>
    <p>{{ review.content }}</p>
    {% endfor %}
    {% else %}
    <p>{% trans "There is no reviews"%}</p>
    {% endif %}

    {% if user.is_authenticated %}
    <div class="fieldWrapper">
        <hr>
        <br/>
        <h4>{% trans "Leave your review:"%}</h4>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.content }}</br>
            <input type="submit" value="{% trans 'Save'%}">
        </form>
    </div>
    {% endif %}
</div>

{% endblock %}

autoservisas/templates/orders.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <h1>{% trans "Orders"%}</h1>
  {% if order_list %}
  <ul>
    {% for order in order_list %}
      <li>
          <img class="rounded-circle" src="{{order.client.profile.picture.url}}">
        <a href="{{ order.id }}">{{ order.car }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>{% trans "We do not have anything"%}</p>
  {% endif %}
  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; {% trans "first"%}</a>
            <a href="?page={{ page_obj.previous_page_number }}">{% trans "back"%}</a>
        {% endif %}

        <span class="current">
            {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">{% trans "forward"%}</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">{% trans "last"%} &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

autoservisas/templates/user_order.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% trans "My order:"%}</h1>
    <hr>
        <ul>
        <img class="rounded-circle" src="{{object.client.profile.picture.url}}">
        <li><strong class="{% if object.is_overdue %}text-danger{% endif %}">{% trans "Car: "%}{{ order.car }}</strong></li>
        <li><strong>{% trans "Due to:"%}</strong> {{object.due_date}}</li>
            {% if object.client == user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'my-order-update' object.id %}">{% trans "Edit"%}</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'my-order-delete' object.id %}">{% trans "Delete"%}</a>
            </div>
            {% endif %}

        <br/>
      </li>
    </ul>
<div style="margin-left:20px;margin-top:20px">
    <h4>{% trans "Services:"%}</h4>
    {% for orderline in order.lines.all %}
    <hr>
    <p>{{ orderline.service }} - {{orderline.qty}}{% trans "pcs. Total: "%} {{orderline.item_sum}} </p>
    {% endfor %}
    <p><strong>{% trans "Total: "%}</strong> {{ order.total_sum }} </p>
    </br>
    <a class="btn btn-primary btn-lg active" href="{% url 'my-orderline' order.pk %}">{% trans "New Order"%}</a>
    <h4>{% trans "Reviews:"%}</h4>
    {% if order.orderreview_set.all %}
    {% for review in order.orderreview_set.all %}
    <hr>
    <strong>{{ review.reviewer }}</strong>, <em>{{ review.date_created}}</em>
    <p>{{ review.content }}</p>
    {% endfor %}
    {% else %}
    <p>{% trans "There is no reviews"%}</p>
    {% endif %}

    {% if user.is_authenticated %}
    <div class="fieldWrapper">
        <hr>
        <br/>
        <h4>{% trans "Leave your review:"%}</h4>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.content }}</br>
            <input type="submit" value="{% trans 'Save'%}">
        </form>
    </div>
    {% endif %}
</div>
{% endblock %}

autoservisas/templates/user_orders.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% trans "My cars"%}</h1>

    {% if order_list %}
    <ul>

      {% for order in order_list %}
        <img class="rounded-circle" src="{{order.client.profile.picture.url}}">
      <li class="{% if order.is_overdue %}text-danger{% endif %}">{{ order.car }}</li>
        <li><strong>{% trans "Due to:"%}</strong> {{order.due_date}}</li>
        <br/>
        <a class="btn btn-primary" href="{{ order.pk }}" role="button">{% trans "Review"%}</a>
        <br>
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>{% trans "You do not have any cars at the moment"%}</p>
    {% endif %}
{% endblock %}